version: '3'
services:
  ddclient_alpine:
    build:
      context: .
      dockerfile: Dockerfile
    # image: alpine:latest
    restart: unless-stopped
    # volumes:
    #   - .:/usr/share/nginx/html
